apiVersion: v1
kind: Service
metadata:
  name: hpc-scheduler-core
  namespace: hpc-system
spec:
  selector:
    app: hpc-scheduler-core
  ports:
    - name: slurmctld
      port: 6817
      targetPort: 6817
    - name: slurmdbd
      port: 6819
      targetPort: 6819
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpc-scheduler-core
  namespace: hpc-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpc-scheduler-core
  template:
    metadata:
      labels:
        app: hpc-scheduler-core
    spec:
      hostname: hpc-scheduler-core
      containers:
        - name: slurmdbd
          image: zaratr/hpc-node:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: HPC_ROLE
              value: slurmdbd
          ports:
            - name: slurmdbd
              containerPort: 6819
          volumeMounts:
            - name: slurm-config
              mountPath: /config
              readOnly: true
            - name: munge-key
              mountPath: /munge-secret
              readOnly: true
        - name: slurmctld
          image: zaratr/hpc-node:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: HPC_ROLE
              value: slurmctld
          ports:
            - name: slurmctld
              containerPort: 6817
          volumeMounts:
            - name: slurm-config
              mountPath: /config
              readOnly: true
            - name: munge-key
              mountPath: /munge-secret
              readOnly: true
            - name: slurm-state
              mountPath: /var/spool/slurm/ctld
      volumes:
        - name: slurm-config
          configMap:
            name: slurm-config
        - name: munge-key
          secret:
            secretName: munge-key
            defaultMode: 0400
        - name: slurm-state
          emptyDir: {}
