apiVersion: v1
kind: Service
metadata:
  name: hpc-compute-nodes
  namespace: hpc-system
spec:
  clusterIP: None
  selector:
    app: hpc-compute-nodes
  ports:
    - name: slurmd
      port: 6818
      targetPort: 6818
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hpc-compute-nodes
  namespace: hpc-system
spec:
  serviceName: hpc-compute-nodes
  replicas: 2
  selector:
    matchLabels:
      app: hpc-compute-nodes
  template:
    metadata:
      labels:
        app: hpc-compute-nodes
    spec:
      containers:
        - name: worker-blade
          image: zaratr/hpc-node:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          env:
            - name: HPC_ROLE
              value: compute
          ports:
            - name: slurmd
              containerPort: 6818
          resources:
            requests:
              cpu: "500m"
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 3Gi
          volumeMounts:
            - name: slurm-config
              mountPath: /config
              readOnly: true
            - name: munge-key
              mountPath: /munge-secret
              readOnly: true
            - name: home
              mountPath: /home/hpcuser
            - name: projects
              mountPath: /projects
            - name: scratch
              mountPath: /scratch
            - name: slurmd-spool
              mountPath: /var/spool/slurm/d
      volumes:
        - name: slurm-config
          configMap:
            name: slurm-config
        - name: munge-key
          secret:
            secretName: munge-key
            defaultMode: 0400
        - name: home
          persistentVolumeClaim:
            claimName: shared-home
        - name: projects
          persistentVolumeClaim:
            claimName: shared-projects
        - name: scratch
          persistentVolumeClaim:
            claimName: shared-scratch
        - name: slurmd-spool
          emptyDir: {}
